BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[books] (
    [id] NVARCHAR(1000) NOT NULL,
    [title] NVARCHAR(1000) NOT NULL,
    [description] NVARCHAR(1000) NOT NULL,
    [bar_code] NVARCHAR(1000) NOT NULL,
    [created_at] DATETIME2 NOT NULL CONSTRAINT [books_created_at_df] DEFAULT CURRENT_TIMESTAMP,
    [updated_at] DATETIME2,
    CONSTRAINT [books_pkey] PRIMARY KEY CLUSTERED ([id]),
    CONSTRAINT [books_bar_code_key] UNIQUE NONCLUSTERED ([bar_code])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
